//Graph
export const ADD_GRAPH_START = "ADD_GRAPH_START";
export const ADD_GRAPH_SUCCESS = "ADD_GRAPH_SUCCESS";
export const ADD_GRAPH_FAILURE = "ADD_GRAPH_FAILURE";

export const EDIT_GRAPH_START = "EDIT_GRAPH_START";
export const EDIT_GRAPH_SUCCESS = "EDIT_GRAPH_SUCCESS";
export const EDIT_GRAPH_FAILURE = "EDIT_GRAPH_FAILURE";

//Graphs
export const GET_GRAPHS_START = "GET_GRAPHS_START";
export const GET_GRAPHS_SUCCESS = "GET_GRAPHS_SUCCESS";
export const GET_GRAPHS_FAILURE = "GET_GRAPHS_FAILURE";

export const DELETE_GRAPH_START = "DELETE_GRAPH_START";
export const DELETE_GRAPH_SUCCESS = "DELETE_GRAPH_SUCCESS";
export const DELETE_GRAPH_FAILURE = "DELETE_GRAPH_FAILURE";

//Dataset
export const ADD_DATASET_START = "ADD_DATASET_START";
export const ADD_DATASET_SUCCESS = "ADD_DATASET_SUCCESS";
export const ADD_DATASET_FAILURE = "ADD_DATASET_FAILURE";

export const EDIT_DATASET_START = "EDIT_DATASET_START";
export const EDIT_DATASET_SUCCESS = "EDIT_DATASET_SUCCESS";
export const EDIT_DATASET_FAILURE = "EDIT_DATASET_FAILURE";

export const DELETE_DATASET_START = "DELETE_DATASET_START";
export const DELETE_DATASET_SUCCESS = "DELETE_DATASET_SUCCESS";
export const DELETE_DATASET_FAILURE = "DELETE_DATASET_FAILURE";
